### ISSUE TITLE
Output on log file

### ISSUE THREAD

**Issue by mordillo123** [zsounder/goconf#1]
Hi zsounder, thanks for your job.
Have you consider the possibility to log [Config] messages on log file? Maybe on the main logging system used on the main program?

Best regards

**Comment by timestee** [comment]
@mordillo123 
Not necessary to do that i think, you could just treat the ` [Config] ...` as tips information.  Actually the operation `ResolveAutoFlag(ops).ValidateAndPanic(ops)` should be complete successful or return an error.  Then log the error message `on the main program` as your advised. 

If you control your service with **Supervisord** or **Monit**, just redirect the stdout and stderr to log file, the ` [Config] ...`  message will be there too.

Perhaps you could initialize a pull request :)

**Comment by mordillo123** [comment]
Thanks @zsounder I'm too newbie to try a pull request. Maybe in the future :-)
